<!--        Navigation bar-->
<nav class="w3-sidenav w3-border w3-quarter m2 w3-col">
    <div class="w3-large w3-text- w3-panel">        
        <a class="w3-light-grey w3-margin-bottom w3-border w3-padding-12 w3-hover-black" href="<?=$baseUrl?>top/index">Before</a>                   
        <a class="w3-light-gray w3-margin-bottom w3-border w3-padding-12 w3-hover-black" href="<?=$baseUrl?>top/index/working">Working</a>
        <a class="w3-light-gray w3-margin-bottom w3-border w3-padding-12 w3-hover-black" href="#">After</a>
    </div>
</nav>
<div class="w3-container sidenav-content">
    <form class="w3-container w3-blue-gray w3-text-white w3-form">
        <h1 class="w3-panel  w3-wide w3-text-shadow-white w3-border-bottom w3-border-orange">Confirm below lists</h1>
        <ul class="w3-ul w3-card-4 w3-border">
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Have a PPM header bar?</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate"> If comment out the Rakuten's image,check remain schema(space) and while still schema clear that.</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Check the banner of height is match?</label></li>
             <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Have comment out Rakuten's event?</label></li>
             <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Have the image with Rakuten word? (Eg.foot_payment)</label></li>
             <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Have comment out QR-Code image?</label></li>
             <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Remain to change the Rakuten Link?</label></li>
             <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Remain the image with asuraku?</label></li>
             <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Have you added pickup item to PPM when pickup item is still?</label></li>
        </ul>
        <a href="#" class="w3-btn w3-green w3-padding-16 w3-hide sidenav-content link-btn">Send Message</a>
    </form>
</div>