<div class="w3-content content w3-khaki w3-round-jumbo w3-padding-12 ">
    <form class="w3-container w3-wide w3-xlarge w3-text-dark-grey">
        <h1>Checkboxes</h1>                    
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox" checked="checked">
            <label class="w3-validate">Top</label></p>
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox">
            <label class="w3-validate"> Gold</label></p>
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Lemon (Disabled)</label></p>
    </form>
</div>
