<!--        Navigation bar-->
<nav class="w3-sidenav w3-border w3-quarter m2 w3-col">
    <div class="w3-large w3-text- w3-panel">        
        <a class="w3-light-grey w3-margin-bottom w3-border w3-padding-12 w3-hover-black" href="#">Before</a>                   
        <a class="w3-light-gray w3-margin-bottom w3-border w3-padding-12 w3-hover-black" href="<?=$baseUrl?>top/index/working">Working</a>
        <a class="w3-light-gray w3-margin-bottom w3-border w3-padding-12 w3-hover-black" href="<?=$baseUrl?>top/index/after">After</a>
    </div>
</nav>
<div class="w3-container sidenav-content">
    <form class="w3-container w3-blue-gray w3-text-white w3-form">
        <h1 class="w3-panel  w3-wide w3-text-shadow-white w3-border-bottom w3-border-orange">Checking All Below</h1>
        <ul class="w3-ul w3-card-4 w3-border">
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Please check the shop is gold or not by going to Rakuten Shop Page.</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">When get the [header, sidebar, footer] from Rakuten, the layout is  needed to same as the layout of orginal website. (Eg.uedakaya)</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">If the shop is open, did you change the status of basic information setting?</label></li>          
        </ul>
        <a href="<?=$baseUrl?>top/index/working" class="w3-btn w3-green w3-padding-16 w3-hide sidenav-content link-btn">Working</a>
    </form>
</div>