<html>
    <head>
        <title>Working Status Check</title>
        <link rel="shortcut icon" href="<?=$baseUrl?>img/favicon.png"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <?php $this->assets->outputCss();              
              ?>
        
    </head>

    <body class="w3-blue-gray ">
        <!--Content -->
        <div class="w3-main">
            <div class="w3-container w3-light-grey w3-top">
                <h2 class="w3-text-blue-gray" id="head_height">SBwork MM</h2>
                <a href="<?=$baseUrl?>" class="w3-display-right w3-btn w3-blue-gray w3-margin-bottom w3-margin-right"><i class="fa fa-home"></i>Home</a>
            </div>
           <?php echo $this->getContent(); 
            $this->assets->outputJs();
            ?>
        </div>
    </body>
</html>    
