<!--        Navigation bar-->
<nav class="w3-sidenav w3-border w3-quarter m2 w3-col">
    <div class="w3-large w3-text-brown w3-panel">                   
        <a class="w3-light-grey w3-margin-bottom w3-padding-12 w3-hover-black w3-border" href="<?=$baseUrl?>product/index">Before</a>                   
        <a class="w3-light-gray w3-margin-bottom w3-padding-12 w3-hover-black w3-border" href="<?=$baseUrl?>product/index/after">After</a>
    </div>
</nav>
<div class="w3-container sidenav-content">
    <form class="w3-container w3-text-white w3-form">
        <h1 class="w3-panel  w3-wide w3-text-shadow-white w3-border-bottom w3-border-orange">Check the follwing procress After migration </h1>
        <ul class="w3-ul w3-card-2 w3-border">
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Have you confirmed,open the product in product management?(Open the PC site and the smart site to the 2nd page and check it)</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">There is an image with NoImage?</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Remain the image with asuraku?</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Option of product is correct?</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Category of product is correct?</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Have comment out QR-Code image?</label></li>
    </form>
</div>
