<!--        Navigation bar-->
<nav class="w3-sidenav w3-border w3-quarter m2 w3-col">
    <div class="w3-container">
    <h3 class="w3-text-shadow w3-border-bottom w3-text-black">Product</h3>
    </div>
    <div class="w3-large w3-text-brown w3-panel">    
                           
        <a class="w3-blue-gray w3-margin-bottom w3-padding-12 w3-border" href="#">Before</a>                   
        <a class="w3-light-gray w3-margin-bottom w3-padding-12 w3-border" href="<?=$baseUrl?>product/index/after">After</a>
    </div>
</nav>
<div class="w3-container sidenav-content">
    <form class="w3-container w3-text-white w3-form">
        <h1 class="w3-panel  w3-wide w3-text-shadow-white w3-border-bottom w3-border-orange">Check the follwing procress before migration </h1>
        <ul class="w3-ul w3-card-2 w3-border">
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Please check the shop is gold or not by going to Rakuten Shop Page.</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Whether the total size of GOLD files is over 100 mb (in that case, images are registered in image management)</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Did you check the STS application instruction.</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Product status at transition.</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">Before edit,there is a product already registered in Ponpare Mall(If the customer want to erase all, first delete all)</label></li>
            <li>
                <input class="w3-check" type="checkbox">
                <label class="w3-validate">If the shop is open, did you change the status of basic information setting?</label></li>
        </ul>        
        <a href="<?=$baseUrl?>product/index/after" class="w3-btn w3-green w3-padding-16 w3-hide sidenav-content link-btn">After</a>
    </form>
</div>
