<!--<div class="w3-content content w3-khaki w3-round-jumbo w3-padding-12 ">
    <form class="w3-container w3-wide w3-xlarge w3-text-dark-grey">
        <h1>Checkboxes</h1>                    
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox" checked="checked">
            <label class="w3-validate">Top</label></p>
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox">
            <label class="w3-validate"> Gold</label></p>
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Lemon (Disabled)</label></p>
    </form>
</div>-->

<div id="myDIV" class="header">
    <h2 style="margin:5px"><b>Before your migration,Please check the follwing facts</b></h2>
  <input type="text" id="myInput" placeholder="Title...">
  <span onclick="newElement()" class="addBtn">Add</span>
</div>

<ul id="myUL">
  <li>1.Whether the total size of GOLD files is over 100 mb (in that case, images are registered in image management)</li>
  <li>2.Did you check the STS application instruction</li>
  <li>3. Product to be migrated</li>
  <li>4. Product status at transition</li>
  <li>5. Before edit,there is a product already registered in Ponpare Mall
	#If the customer want to erase all, first delete all</li>
  <li>6. Move TOP Page</li>
  <li>7. When get the [header, sidebar, footer] from Rakuten, the layout is  needed to same as the layout of orginal website.</li>
  <li>8.If the shop is open, did you change the status of basic information setting?</li>
</ul>
