<!--<div class="w3-content content w3-khaki w3-round-jumbo w3-padding-12 ">
    <form class="w3-container w3-wide w3-xlarge w3-text-dark-grey">
        <h1>Checkboxes</h1>                    
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox" checked="checked">
            <label class="w3-validate">Top</label></p>
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox">
            <label class="w3-validate"> Gold</label></p>
        <p class="w3-card-8 w3-padding-16 w3-padding-left">
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Lemon (Disabled)</label></p>
    </form>
</div>-->
<div class="w3-content content w3-white w3-padding-12 ">
    <form class="w3-container w3-text-dark-grey">
        <h1 class="w3-panel  w3-wide w3-text-blue-gre w3-border-bottom w3-border-orange">Checking of Top Page Working Process </h1>
        <ul class="w3-ul w3-card-4">
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Have the smartphone TOP page?(GOLD of sp, or RMS)</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">  While there is not data in RMS,get the source code from the browser.</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">If comment out the Rakuten's image,check remain schema(space) and while still schema clear that.</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Check the banner of height is match?</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Have a PPM header bar?</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Have comment out Rakuten's event?</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Have the image with Rakuten? (Eg.foot_payment)</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Have comment out QR-Code image?</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Remain to change the Rakuten Link?</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Is using [iframe] in the CSV file?</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">Remain the image with asuraku?</label></li>
        <li>
            <input class="w3-check" type="checkbox">
            <label class="w3-validate">There is an pick up item?</label></li>
        </ul>
         <button class="w3-btn w3-green w3-hide">Send Message</button>
    </form>
</div>