<div class="w3-content content w3-row">
    <li class="w3-dropdown-hover w3-col m5 w3-blue-grey w3-card-4 w3-padding-24 w3-center">
        <a href="<?=$baseUrl?>top/index" class="">Top</a>     
    </li>        
    <li class="w3-dropdown-hover w3-margin-left w3-card-4 w3-col m5 w3-padding-24 w3-deep-orange w3-center">
        <a href="<?=$baseUrl?>product/index">Product </a>
    </li>    
</div>
