<div class="w3-content content w3-row">
    <li class="w3-dropdown-hover w3-col m5 w3-blue-grey w3-card-4 w3-padding-24 w3-center">
        <a href="#" class="">Top <i class="fa fa-caret-down"></i></a>
        <div class="w3-dropdown-content w3-blue-grey w3-card-4 w3-col m12 w3-padding-24 w3-margin-top">
            <a href="<?=$baseUrl?>top/index/gold" class="w3-padding-16">Gold</a>
            <a href="<?=$baseUrl?>top/index/normal" class="w3-padding-16">Normal</a>            
        </div>
    </li>        
    <li class="w3-dropdown-hover w3-margin-left w3-card-4 w3-col m5 w3-padding-24 w3-light-blue w3-center">
        <a href="<?=$baseUrl?>product/index/normal">Product </a>
    </li>    
</div>
